[[redirects]]
  from = "/no-where/*"
  to = "/welcome-to-the-blog"
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/no-where/*"
  to = "/hello-world"
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/no-where/*"
  to = "/another-new-post/"
